select = [
  "E",   # pycodestyle error
  "F",   # pyflakes
  "D",   # pydocstyle
  "PL",  # pylint
  "N",   # pep8-naming
  "B",   # flake8-bugbear (detects likely bugs)
  "G",   # flake8-logging-format (complains about logging)
  "SIM", # flake8-simplify (suggests code simplifications)
  "RUF", # Ruff-introduced misc rules
]
ignore = [
  "PLW0603",  # Global statement
  "B019",     # Usage of functools.lru_cache
  "PLR0912",
  "PLR0913",  # Too many function arguments
  "B905",     # zip strict argument
  "SIM105",
]
line-length = 120

[pydocstyle]
convention = "google"

[per-file-ignores]
"**/__init__.py" = ["F401", "F403"]
"perseus/client/api.py" = ["PLR2004"]
"perseus/models.py" = ["N805"]
"perseus/server/main.py" = ["B008"]
