name: Push Docker image

on:
  push:
    branches:
      - multi-arch-docker-build
    tags:
      - zeus-v*
    paths:
      - '.github/workflows/push_docker.yaml'
      - 'capriccio/**'
      - 'examples/**'
      - 'trace/**'
      - 'zeus/**'
      - 'zeus_monitor/**'
      - '.dockerignore'
      - 'docker/Dockerfile'
      - 'LICENSE'
      - 'setup.py'
      - 'pyproject.toml'
  pull_request:
    branches:
      - multi-arch-docker-build
jobs:
  build_and_push:
    if: github.repository_owner == 'ml-energy'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            symbioticlab/zeus
            mlenergy/zeus
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=schedule
            type=sha
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=mlenergy/zeus:buildcache
          cache-to: type=registry,ref=mlenergy/zeus:buildcache,mode=max
          build-args: TARGETARCH=amd64
          platforms: ${{ matrix.platform }}

